/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200ResponseNetworks1V6 {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "prefix")]
    pub prefix: f64,
}

impl GetClientConfig200ResponseNetworks1V6 {
    pub fn new(address: String, prefix: f64) -> GetClientConfig200ResponseNetworks1V6 {
        GetClientConfig200ResponseNetworks1V6 {
            address,
            prefix,
        }
    }
}

