/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSourceDevice200ResponseConfigInterface {
    #[serde(rename = "addresses")]
    pub addresses: Box<models::GetSourceDevice200ResponseConfigInterfaceAddresses>,
}

impl GetSourceDevice200ResponseConfigInterface {
    pub fn new(addresses: models::GetSourceDevice200ResponseConfigInterfaceAddresses) -> GetSourceDevice200ResponseConfigInterface {
        GetSourceDevice200ResponseConfigInterface {
            addresses: Box::new(addresses),
        }
    }
}

