/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSourceDevice200ResponseConfigServices {
    #[serde(rename = "http_proxy")]
    pub http_proxy: String,
}

impl GetSourceDevice200ResponseConfigServices {
    pub fn new(http_proxy: String) -> GetSourceDevice200ResponseConfigServices {
        GetSourceDevice200ResponseConfigServices {
            http_proxy,
        }
    }
}

