/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSourceDevice200ResponseConfig {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "interface")]
    pub interface: Box<models::GetSourceDevice200ResponseConfigInterface>,
    #[serde(rename = "peers")]
    pub peers: Vec<models::GetSourceDevice200ResponseConfigPeers>,
    #[serde(rename = "services")]
    pub services: Box<models::GetSourceDevice200ResponseConfigServices>,
}

impl GetSourceDevice200ResponseConfig {
    pub fn new(client_id: String, interface: models::GetSourceDevice200ResponseConfigInterface, peers: Vec<models::GetSourceDevice200ResponseConfigPeers>, services: models::GetSourceDevice200ResponseConfigServices) -> GetSourceDevice200ResponseConfig {
        GetSourceDevice200ResponseConfig {
            client_id,
            interface: Box::new(interface),
            peers,
            services: Box::new(services),
        }
    }
}

