/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200Response {
    #[serde(rename = "captive_portal")]
    pub captive_portal: Vec<models::GetClientConfig200ResponseCaptivePortal>,
    #[serde(rename = "denylist")]
    pub denylist: Vec<models::GetClientConfig200ResponseDenylist>,
    #[serde(rename = "premium_data_bytes")]
    pub premium_data_bytes: f64,
    #[serde(rename = "referral_reward_bytes")]
    pub referral_reward_bytes: f64,
}

impl GetClientConfig200Response {
    pub fn new(captive_portal: Vec<models::GetClientConfig200ResponseCaptivePortal>, denylist: Vec<models::GetClientConfig200ResponseDenylist>, premium_data_bytes: f64, referral_reward_bytes: f64) -> GetClientConfig200Response {
        GetClientConfig200Response {
            captive_portal,
            denylist,
            premium_data_bytes,
            referral_reward_bytes,
        }
    }
}

