/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200ResponseNetworks1 {
    #[serde(rename = "v4")]
    pub v4: Vec<models::GetClientConfig200ResponseNetworks1V4>,
    #[serde(rename = "v6")]
    pub v6: Vec<models::GetClientConfig200ResponseNetworks1V6>,
}

impl GetClientConfig200ResponseNetworks1 {
    pub fn new(v4: Vec<models::GetClientConfig200ResponseNetworks1V4>, v6: Vec<models::GetClientConfig200ResponseNetworks1V6>) -> GetClientConfig200ResponseNetworks1 {
        GetClientConfig200ResponseNetworks1 {
            v4,
            v6,
        }
    }
}

