/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSourceDevice200ResponseConfigInterfaceAddresses {
    #[serde(rename = "v4")]
    pub v4: String,
    #[serde(rename = "v6")]
    pub v6: String,
}

impl GetSourceDevice200ResponseConfigInterfaceAddresses {
    pub fn new(v4: String, v6: String) -> GetSourceDevice200ResponseConfigInterfaceAddresses {
        GetSourceDevice200ResponseConfigInterfaceAddresses {
            v4,
            v6,
        }
    }
}

