/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200ResponseCaptivePortal {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "networks")]
    pub networks: Vec<models::GetClientConfig200ResponseNetworks>,
}

impl GetClientConfig200ResponseCaptivePortal {
    pub fn new(name: String, networks: Vec<models::GetClientConfig200ResponseNetworks>) -> GetClientConfig200ResponseCaptivePortal {
        GetClientConfig200ResponseCaptivePortal {
            name,
            networks,
        }
    }
}

