/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200ResponseNetworks1V4 {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "netmask")]
    pub netmask: String,
}

impl GetClientConfig200ResponseNetworks1V4 {
    pub fn new(address: String, netmask: String) -> GetClientConfig200ResponseNetworks1V4 {
        GetClientConfig200ResponseNetworks1V4 {
            address,
            netmask,
        }
    }
}

