/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientConfig200ResponseDenylist {
    #[serde(rename = "android-packages", skip_serializing_if = "Option::is_none")]
    pub android_packages: Option<Vec<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Box<models::GetClientConfig200ResponseNetworks1>>,
    #[serde(rename = "visible")]
    pub visible: bool,
}

impl GetClientConfig200ResponseDenylist {
    pub fn new(name: String, visible: bool) -> GetClientConfig200ResponseDenylist {
        GetClientConfig200ResponseDenylist {
            android_packages: None,
            name,
            networks: None,
            visible,
        }
    }
}

