/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "fcm_token")]
    pub fcm_token: String,
    #[serde(rename = "install_id")]
    pub install_id: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "locale")]
    pub locale: String,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "tos")]
    pub tos: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl RegisterRequest {
    pub fn new(fcm_token: String, install_id: String, key: String, locale: String, model: String, tos: String, r#type: String) -> RegisterRequest {
        RegisterRequest {
            fcm_token,
            install_id,
            key,
            locale,
            model,
            tos,
            r#type,
        }
    }
}

