/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetAccountLicense200Response {
    #[serde(rename = "license")]
    pub license: String,
}

impl ResetAccountLicense200Response {
    pub fn new(license: String) -> ResetAccountLicense200Response {
        ResetAccountLicense200Response {
            license,
        }
    }
}

