/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSourceDeviceRequest {
    #[serde(rename = "key")]
    pub key: String,
}

impl UpdateSourceDeviceRequest {
    pub fn new(key: String) -> UpdateSourceDeviceRequest {
        UpdateSourceDeviceRequest {
            key,
        }
    }
}

