/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 536
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSourceDevice200Response {
    #[serde(rename = "account")]
    pub account: Box<models::UpdateSourceDevice200ResponseAccount>,
    #[serde(rename = "config")]
    pub config: Box<models::GetSourceDevice200ResponseConfig>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "fcm_token")]
    pub fcm_token: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "install_id")]
    pub install_id: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "locale")]
    pub locale: String,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "place")]
    pub place: f64,
    #[serde(rename = "tos")]
    pub tos: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "updated")]
    pub updated: String,
    #[serde(rename = "waitlist_enabled")]
    pub waitlist_enabled: bool,
    #[serde(rename = "warp_enabled")]
    pub warp_enabled: bool,
}

impl UpdateSourceDevice200Response {
    pub fn new(account: models::UpdateSourceDevice200ResponseAccount, config: models::GetSourceDevice200ResponseConfig, created: String, enabled: bool, fcm_token: String, id: String, install_id: String, key: String, locale: String, model: String, name: String, place: f64, tos: String, r#type: String, updated: String, waitlist_enabled: bool, warp_enabled: bool) -> UpdateSourceDevice200Response {
        UpdateSourceDevice200Response {
            account: Box::new(account),
            config: Box::new(config),
            created,
            enabled,
            fcm_token,
            id,
            install_id,
            key,
            locale,
            model,
            name,
            place,
            tos,
            r#type,
            updated,
            waitlist_enabled,
            warp_enabled,
        }
    }
}

