[package]
name = "warp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
rand = "0.8.5"
reqwest = { version = "0.12.8", default-features = false }
time = { version = "0.3.36", features = ["formatting"] }
warp-raw-api = { path = "../warp-raw-api" }
